// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ExerciseCardController from "./exercise_card_controller"
application.register("exercise-card", ExerciseCardController)

import ExerciseFormController from "./exercise_form_controller"
application.register("exercise-form", ExerciseFormController)

import ImplementCountController from "./implement_count_controller"
application.register("implement-count", ImplementCountController)

import LadderFieldsController from "./ladder_fields_controller"
application.register("ladder-fields", LadderFieldsController)

import LadderStepController from "./ladder_step_controller"
application.register("ladder-step", LadderStepController)

import LiftingScoreController from "./lifting_score_controller"
application.register("lifting-score", LiftingScoreController)

import LogExerciseController from "./log_exercise_controller"
application.register("log-exercise", LogExerciseController)

import MovementSelectController from "./movement_select_controller"
application.register("movement-select", MovementSelectController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import RepMaxRowController from "./rep_max_row_controller"
application.register("rep-max-row", RepMaxRowController)

import ScheduleDatePickerController from "./schedule_date_picker_controller"
application.register("schedule-date-picker", ScheduleDatePickerController)

import SegmentCardController from "./segment_card_controller"
application.register("segment-card", SegmentCardController)

import SortableListController from "./sortable_list_controller"
application.register("sortable-list", SortableListController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)

import WorkoutSearchController from "./workout_search_controller"
application.register("workout-search", WorkoutSearchController)
