// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import WorkoutSearchController from "./workout_search_controller.js"
application.register("workout-search", WorkoutSearchController)

import MovementSelectController from "./movement_select_controller.js"
application.register("movement-select", MovementSelectController)

import ExerciseFormController from "./exercise_form_controller.js"
application.register("exercise-form", ExerciseFormController)

import ExerciseCardController from "./exercise_card_controller.js"
application.register("exercise-card", ExerciseCardController)

import ImplementCountController from "./implement_count_controller.js"
application.register("implement-count", ImplementCountController)

import LadderFieldsController from "./ladder_fields_controller.js"
application.register("ladder-fields", LadderFieldsController)

import LadderStepController from "./ladder_step_controller.js"
application.register("ladder-step", LadderStepController)

import LogExerciseController from "./log_exercise_controller.js"
application.register("log-exercise", LogExerciseController)

import SegmentCardController from "./segment_card_controller.js"
application.register("segment-card", SegmentCardController)

import NestedFormController from "./nested_form_controller.js"
application.register("nested-form", NestedFormController)

import SortableListController from "./sortable_list_controller.js"
application.register("sortable-list", SortableListController)
