require:
  - rubocop-performance
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - vendor/**/*
    - db/**/*
    - tmp/**/*
    - bin/**/*
    - node_modules/**/*
    - config/initializers/simple_form_bootstrap.rb
  NewCops: enable
  ExtraDetails: true
  TargetRubyVersion: 3.1

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/LineLength:
  Max: 160
  Exclude:
    - config/**/*

Metrics/AbcSize:
  Max: 20
  Exclude:
    - app/models/ability.rb

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - config/**/*

Metrics/MethodLength:
  CountComments: false
  Max: 20

Performance/AncestorsInclude:
  Enabled: false

Performance/BigDecimalWithNumericArgument:
  Enabled: false

Performance/RedundantSortBlock:
  Enabled: false

Performance/RedundantStringChars:
  Enabled: false

Performance/ReverseFirst:
  Enabled: false

Performance/SortReverse:
  Enabled: false

Performance/Squeeze:
  Enabled: false

Performance/StringInclude:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Exclude:
    - app/controllers/concerns/*

Security/Open:
  Exclude:
    - app/models/user.rb

Style/ClassAndModuleChildren:
  Description: 'Checks style of children classes and modules.'
  Enabled: true
  EnforcedStyle: nested

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/ExpandPathArguments:
  Exclude:
    - Rakefile
    - test/test_helper.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
