# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
admin = User.find_or_create_by(email: 'admin@wod-tracker.com') do |u|
  u.first_name = 'ADMIN'
  u.last_name = 'ADMIN'
  u.sex = :male
  u.weight = 0
  u.role = :admin
  u.password = Rails.application.credentials.admin_password
end

# Movements
abmat_sit_up = Movement.find_or_create_by(name: 'AbMat Sit-up')
air_squat = Movement.find_or_create_by(name: 'Air Squat')
back_extensions = Movement.find_or_create_by(name: 'Back Extensions')
back_scale = Movement.find_or_create_by(name: 'Back Scale')
back_squat = Movement.find_or_create_by(name: 'Back Squat')
bar_muscle_up = Movement.find_or_create_by(name: 'Bar Muscle-up')
bar_facing_burpee = Movement.find_or_create_by(name: 'Bar-facing Burpee')
barbell_front_rack_lunge = Movement.find_or_create_by(name: 'Barbell Front-rack Lunge')
bench_press = Movement.find_or_create_by(name: 'Bench Press')
bent_over_row = Movement.find_or_create_by(name: 'Bent-over Row')
body_blaster = Movement.find_or_create_by(name: 'Body Blaster')
box_jump = Movement.find_or_create_by(name: 'Box Jump')
box_jump_over = Movement.find_or_create_by(name: 'Box Jump-over')
box_step_up = Movement.find_or_create_by(name: 'Box Step-up')
burpee = Movement.find_or_create_by(name: 'Burpee')
burpee_box_jump = Movement.find_or_create_by(name: 'Burpee Box Jump')
burpee_box_jump_over = Movement.find_or_create_by(name: 'Burpee Box Jump-over')
burpee_pull_up = Movement.find_or_create_by(name: 'Burpee Pull-up')
butterfly_pull_up = Movement.find_or_create_by(name: 'Butterfly Pull-up')
chest_to_bar_pull_up = Movement.find_or_create_by(name: 'Chest-to-bar Pull-up')
chest_to_wall_handstand_push_up = Movement.find_or_create_by(name: 'Chest-to-wall Handstand Push-up')
clean = Movement.find_or_create_by(name: 'Clean')
clean_and_jerk = Movement.find_or_create_by(name: 'Clean and Jerk')
clean_and_push_jerk = Movement.find_or_create_by(name: 'Clean and Push Jerk')
clean_squat = Movement.find_or_create_by(name: 'Clean Squat')
deadlift = Movement.find_or_create_by(name: 'Deadlift')
dip = Movement.find_or_create_by(name: 'Dip')
double_under = Movement.find_or_create_by(name: 'Double-under')
dumbbell_bench_press = Movement.find_or_create_by(name: 'Dumbbell Bench Press')
dumbbell_box_step_up = Movement.find_or_create_by(name: 'Dumbbell Box Step-up')
dumbbell_clean = Movement.find_or_create_by(name: 'Dumbbell Clean')
dumbbell_deadlift = Movement.find_or_create_by(name: 'Dumbbell Deadlift')
dumbbell_farmers_carry = Movement.find_or_create_by(name: 'Dumbbell Farmers Carry')
dumbbell_front_squat = Movement.find_or_create_by(name: 'Dumbbell Front Squat')
dumbbell_front_rack_lunge = Movement.find_or_create_by(name: 'Dumbbell Front-rack Lunge')
dumbbell_hang_clean = Movement.find_or_create_by(name: 'Dumbbell Hang Clean')
dumbbell_hang_clean_and_jerk = Movement.find_or_create_by(name: 'Dumbbell Hang Clean and Jerk')
dumbbell_hang_power_clean = Movement.find_or_create_by(name: 'Dumbbell Hang Power Clean')
dumbbell_overhead_squat = Movement.find_or_create_by(name: 'Dumbbell Overhead Squat')
dumbbell_overhead_walking_lunge = Movement.find_or_create_by(name: 'Dumbbell Overhead Walking Lunge')
dumbbell_power_clean = Movement.find_or_create_by(name: 'Dumbbell Power Clean')
dumbbell_power_snatch = Movement.find_or_create_by(name: 'Dumbbell Power Snatch')
dumbbell_push_jerk = Movement.find_or_create_by(name: 'Dumbbell Push Jerk')
dumbbell_push_press = Movement.find_or_create_by(name: 'Dumbbell Push Press')
dumbbell_squat_snatch = Movement.find_or_create_by(name: 'Dumbbell Squat Snatch')
dumbbell_thruster = Movement.find_or_create_by(name: 'Dumbbell Thruster')
dumbbell_turkish_get_up = Movement.find_or_create_by(name: 'Dumbbell Turkish Get-up')
forward_roll_from_support = Movement.find_or_create_by(name: 'Forward Roll From Support')
freestanding_handstand_push_up = Movement.find_or_create_by(name: 'Freestanding Handstand Push-up')
freestanding_shoulder_tap = Movement.find_or_create_by(name: 'Freestanding Shoulder Tap')
front_scale = Movement.find_or_create_by(name: 'Front Scale')
front_squat = Movement.find_or_create_by(name: 'Front Squat')
ghd_back_extension = Movement.find_or_create_by(name: 'GHD Back Extension')
ghd_hip_and_back_extension = Movement.find_or_create_by(name: 'GHD Hip and Back Extension')
ghd_hip_extension = Movement.find_or_create_by(name: 'GHD Hip Extension')
ghd_sit_up = Movement.find_or_create_by(name: 'GHD Sit-up')
glide_kip = Movement.find_or_create_by(name: 'Glide Kip')
good_morning = Movement.find_or_create_by(name: 'Good Morning')
ground_to_overhead = Movement.find_or_create_by(name: 'Ground to Overhead')
handstand = Movement.find_or_create_by(name: 'Handstand')
handstand_pirouette = Movement.find_or_create_by(name: 'Handstand Pirouette')
handstand_push_up = Movement.find_or_create_by(name: 'Handstand Push-up')
handstand_walk = Movement.find_or_create_by(name: 'Handstand Walk')
hang_clean = Movement.find_or_create_by(name: 'Hang Clean')
hang_clean_and_push_jerk = Movement.find_or_create_by(name: 'Hang Clean and Push Jerk')
hang_power_clean = Movement.find_or_create_by(name: 'Hang Power Clean')
hang_power_snatch = Movement.find_or_create_by(name: 'Hang Power Snatch')
hang_snatch = Movement.find_or_create_by(name: 'Hang Snatch')
hanging_l_sit = Movement.find_or_create_by(name: 'Hanging L-sit')
hip_extensions = Movement.find_or_create_by(name: 'Hip Extensions')
inverted_burpee = Movement.find_or_create_by(name: 'Inverted Burpee')
jerk = Movement.find_or_create_by(name: 'Jerk')
jumping_jack = Movement.find_or_create_by(name: 'Jumping Jack')
jumping_lunge = Movement.find_or_create_by(name: 'Jumping Lunge')
kettlebell_snatch = Movement.find_or_create_by(name: 'Kettlebell Snatch')
kettlebell_sumo_hi_pull = Movement.find_or_create_by(name: 'Kettlebell Sumo Hi Pull')
kettlebell_swing = Movement.find_or_create_by(name: 'Kettlebell Swing')
l_pull_up = Movement.find_or_create_by(name: 'L Pull-up')
l_sit_hold_on_matador = Movement.find_or_create_by(name: 'L Sit Hold on Matador')
l_sit = Movement.find_or_create_by(name: 'L-sit')
l_sit_on_rings = Movement.find_or_create_by(name: 'L-sit on Rings')
l_sit_rope_climb = Movement.find_or_create_by(name: 'L-sit Rope Climb')
l_sit_to_shoulder_stand = Movement.find_or_create_by(name: 'L-sit to Shoulder Stand')
lateral_burpee_over_dumbbell = Movement.find_or_create_by(name: 'Lateral Burpee Over Dumbbell')
lateral_over_barbell_burpee = Movement.find_or_create_by(name: 'Lateral Over Barbell Burpee')
legless_rope_climb = Movement.find_or_create_by(name: 'Legless Rope Climb')
lunge = Movement.find_or_create_by(name: 'Lunge')
lunge_with_plate_overhead = Movement.find_or_create_by(name: 'Lunge with plate overhead')
medicine_ball_box_step_over = Movement.find_or_create_by(name: 'Medicine-ball Box Step-over')
medicine_ball_clean = Movement.find_or_create_by(name: 'Medicine-ball Clean')
modified_rope_climb = Movement.find_or_create_by(name: 'Modified Rope Climb')
muscle_snatch = Movement.find_or_create_by(name: 'Muscle Snatch')
muscle_up = Movement.find_or_create_by(name: 'Muscle-up')
over_the_bar_burpee = Movement.find_or_create_by(name: 'Over the bar Burpee')
over_the_medball_burpee = Movement.find_or_create_by(name: 'Over the medball Burpee')
overhead_dumbbell_lunge = Movement.find_or_create_by(name: 'Overhead Dumbbell Lunge')
overhead_squat = Movement.find_or_create_by(name: 'Overhead Squat')
power_clean = Movement.find_or_create_by(name: 'Power Clean')
power_clean_and_split_jerk = Movement.find_or_create_by(name: 'Power Clean and Split Jerk')
power_snatch = Movement.find_or_create_by(name: 'Power Snatch')
pull_over = Movement.find_or_create_by(name: 'Pull-over')
pull_up = Movement.find_or_create_by(name: 'Pull-up')
push_jerk = Movement.find_or_create_by(name: 'Push Jerk')
push_press = Movement.find_or_create_by(name: 'Push Press')
push_up = Movement.find_or_create_by(name: 'Push-up')
deficit_push_up = Movement.find_or_create_by(name: 'Deficit Push-up')
renegade_row = Movement.find_or_create_by(name: 'Renegade Row')
rest = Movement.find_or_create_by(name: 'Rest')
ring_dip = Movement.find_or_create_by(name: 'Ring Dip')
ring_muscle_up = Movement.find_or_create_by(name: 'Ring Muscle-up')
ring_push_up = Movement.find_or_create_by(name: 'Ring Push-up')
ring_row = Movement.find_or_create_by(name: 'Ring Row')
rope_climb = Movement.find_or_create_by(name: 'Rope Climb')
row = Movement.find_or_create_by(name: 'Row')
run = Movement.find_or_create_by(name: 'Run')
shoot_through = Movement.find_or_create_by(name: 'Shoot-through')
shoulder_press = Movement.find_or_create_by(name: 'Shoulder Press')
shoulder_to_overhead = Movement.find_or_create_by(name: 'Shoulder to Overhead')
shuttle_run = Movement.find_or_create_by(name: 'Shuttle Run')
single_leg_squat_pistol = Movement.find_or_create_by(name: 'Single-leg Squat (Pistol)')
single_under = Movement.find_or_create_by(name: 'Single-under')
sit_up = Movement.find_or_create_by(name: 'Sit-up')
skin_the_cat = Movement.find_or_create_by(name: 'Skin the Cat')
slam_ball = Movement.find_or_create_by(name: 'Slam Ball')
sled_drag = Movement.find_or_create_by(name: 'Sled Drag')
sled_pull = Movement.find_or_create_by(name: 'Sled Pull')
snatch = Movement.find_or_create_by(name: 'Snatch')
snatch_balance = Movement.find_or_create_by(name: 'Snatch Balance')
sots_press = Movement.find_or_create_by(name: 'Sots Press')
split_clean = Movement.find_or_create_by(name: 'Split Clean')
split_jerk = Movement.find_or_create_by(name: 'Split Jerk')
split_snatch = Movement.find_or_create_by(name: 'Split Snatch')
straddle_press_to_handstand = Movement.find_or_create_by(name: 'Straddle Press to Handstand')
strict_bar_muscle_up = Movement.find_or_create_by(name: 'Strict Bar Muscle-up')
strict_chest_to_bar_pull_up = Movement.find_or_create_by(name: 'Strict Chest-to-bar Pull-up')
strict_handstand_push_up = Movement.find_or_create_by(name: 'Strict Handstand Push-up')
strict_knees_to_elbows = Movement.find_or_create_by(name: 'Strict Knees-to-elbows')
strict_muscle_up = Movement.find_or_create_by(name: 'Strict Muscle-up')
strict_pull_up = Movement.find_or_create_by(name: 'Strict Pull-up')
strict_toes_to_bar = Movement.find_or_create_by(name: 'Strict Toes-to-bar')
strict_toes_to_rings = Movement.find_or_create_by(name: 'Strict Toes-to-rings')
sumo_deadlift = Movement.find_or_create_by(name: 'Sumo Deadlift')
sumo_deadlift_high_pull = Movement.find_or_create_by(name: 'Sumo Deadlift High Pull')
swim = Movement.find_or_create_by(name: 'Swim')
swing_to_backward_roll_to_support = Movement.find_or_create_by(name: 'Swing to Backward Roll to Support')
tempo_jerk = Movement.find_or_create_by(name: 'Tempo Jerk')
thruster = Movement.find_or_create_by(name: 'Thruster')
toes_to_bar = Movement.find_or_create_by(name: 'Toes to Bar')
toes_to_bar_pull_up = Movement.find_or_create_by(name: 'Toes to Bar + Pull-up')
tuck_up = Movement.find_or_create_by(name: 'Tuck-up')
v_up = Movement.find_or_create_by(name: 'V-up')
walking_lunge = Movement.find_or_create_by(name: 'Walking Lunge')
wall_walk = Movement.find_or_create_by(name: 'Wall Walk')
wall_ball_shot = Movement.find_or_create_by(name: 'Wall-ball Shot')
windshield_wiper = Movement.find_or_create_by(name: 'Windshield Wiper')
zercher_squat = Movement.find_or_create_by(name: 'Zercher Squat')

# Movements first introduced by the Hero workouts
bear_crawl = Movement.find_or_create_by(name: 'Bear Crawl')
bike = Movement.find_or_create_by(name: 'Bike')
broad_jump = Movement.find_or_create_by(name: 'Broad Jump')
barbell_back_rack_step_up = Movement.find_or_create_by(name: 'Barbell Back-rack Step-up')
barbell_step_up = Movement.find_or_create_by(name: 'Barbell Step-up')
bar_hang = Movement.find_or_create_by(name: 'Bar Hang')
burpee_bar_muscle_up = Movement.find_or_create_by(name: 'Burpee Bar Muscle-up')
burpee_chest_to_bar_pull_up = Movement.find_or_create_by(name: 'Burpee Chest-to-bar Pull-up')
burpee_muscle_up = Movement.find_or_create_by(name: 'Burpee Muscle-up')
burpee_pull_up = Movement.find_or_create_by(name: 'Burpee Pull-up')
burpee_to_target = Movement.find_or_create_by(name: 'Burpee to Target')
box_step_over = Movement.find_or_create_by(name: 'Box Step-over')
deficit_handstand_push_up = Movement.find_or_create_by(name: 'Deficit Handstand Push-up')
dumbbell_burpee_deadlift = Movement.find_or_create_by(name: 'Dumbbell Burpee Deadlift')
dumbbell_hang_split_snatch = Movement.find_or_create_by(name: 'Dumbbell Hang Split Snatch')
dumbbell_hang_squat_clean = Movement.find_or_create_by(name: 'Dumbbell Hang Squat Clean')
dumbbell_split_clean = Movement.find_or_create_by(name: 'Dumbbell Split Clean')
dumbbell_squat_clean = Movement.find_or_create_by(name: 'Dumbbell Squat Clean')
dumbbell_squat_clean_thruster = Movement.find_or_create_by(name: 'Dumbbell Squat Clean Thruster')
dumbbell_waiters_walk = Movement.find_or_create_by(name: 'Dumbbell Waiters Walk')
farmers_carry = Movement.find_or_create_by(name: 'Farmers Carry')
forward_roll = Movement.find_or_create_by(name: 'Forward Roll')
hand_release_push_up = Movement.find_or_create_by(name: 'Hand-release Push-up')
hang_squat_clean = Movement.find_or_create_by(name: 'Hang Squat Clean')
hanging_hip_touch = Movement.find_or_create_by(name: 'Hanging Hip Touch')
inverted_ring_lower = Movement.find_or_create_by(name: 'Inverted Ring Lower')
jerk = Movement.find_or_create_by(name: 'Jerk')
kettlebell_clean_and_jerk = Movement.find_or_create_by(name: 'Kettlebell Clean and Jerk')
kettlebell_goblet_squat = Movement.find_or_create_by(name: 'Kettlebell Goblet Squat')
kettlebell_thruster = Movement.find_or_create_by(name: 'Kettlebell Thruster')
knees_to_elbows = Movement.find_or_create_by(name: 'Knees-to-elbows')
overhead_walk = Movement.find_or_create_by(name: 'Overhead Walk')
overhead_walking_lunge = Movement.find_or_create_by(name: 'Overhead Walking Lunge')
parallette_handstand_push_up = Movement.find_or_create_by(name: 'Parallette Handstand Push-up')
plate_carry = Movement.find_or_create_by(name: 'Plate Carry')
ring_handstand_push_up = Movement.find_or_create_by(name: 'Ring Handstand Push-up')
sandbag_carry = Movement.find_or_create_by(name: 'Sandbag Carry')
sandbag_clean = Movement.find_or_create_by(name: 'Sandbag Clean')
shuttle_run = Movement.find_or_create_by(name: 'Shuttle Run')
sled_push = Movement.find_or_create_by(name: 'Sled Push')
squat_clean_thruster = Movement.find_or_create_by(name: 'Squat Clean Thruster')
squat_snatch = Movement.find_or_create_by(name: 'Squat Snatch')
stiff_legged_deadlift = Movement.find_or_create_by(name: 'Stiff-legged Deadlift')
strict_burpee_pull_up = Movement.find_or_create_by(name: 'Strict Burpee Pull-up')
toes_to_rings = Movement.find_or_create_by(name: 'Toes-to-rings')
triple_under = Movement.find_or_create_by(name: 'Triple-under')
turkish_get_up = Movement.find_or_create_by(name: 'Turkish Get-up')
wall_ball_two_for_one = Movement.find_or_create_by(name: 'Wall-ball Two-for-one')
weighted_pull_up = Movement.find_or_create_by(name: 'Weighted Pull-up')

# Movements first introduced by the partner/team Hero workouts
barbell_carry = Movement.find_or_create_by(name: 'Barbell Carry')
buddy_carry = Movement.find_or_create_by(name: 'Buddy Carry')
burpee_over_rower = Movement.find_or_create_by(name: 'Burpee Over Rower')
dumbbell_bent_over_row = Movement.find_or_create_by(name: 'Dumbbell Bent-over Row')
dumbbell_floor_press = Movement.find_or_create_by(name: 'Dumbbell Floor Press')
dumbbell_lunge = Movement.find_or_create_by(name: 'Dumbbell Lunge')
flutter_kick = Movement.find_or_create_by(name: 'Flutter Kick')
handstand_hold = Movement.find_or_create_by(name: 'Handstand Hold')

# Programs
CF_PROGRAM = Program.find_or_create_by(name: 'Crossfit.com')
CF_PROGRAM.subscriptions.find_or_create_by(user: admin) do |subscription|
  subscription.role = :owner
end

%w[
  benchmark_workouts
  hero_workouts
  open_workouts
  cf_workouts
].each do |seed_file|
  seed_path = Rails.root.join('db/seeds', "#{seed_file}.rb")
  # Evaluate local seed files in this binding so movement locals are shared.
  # rubocop:disable Security/Eval
  eval(seed_path.read, binding, seed_path.to_s)
  # rubocop:enable Security/Eval
end
