name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.6
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: runner
          POSTGRES_DB: wodtracker_test
          POSTGRES_PASSWORD: ""
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Install PostgreSQL client
        run: sudo apt-get -yqq install libpq-dev

      # https://github.com/guard/listen/blob/master/README.md#the-technical-details
      - name: Adjust inotify listeners for Listen
        run: |
          sudo sysctl fs.inotify.max_user_watches=524288
          sudo sysctl -p

      # Install Ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.3
          bundler-cache: true

      # Install NodeJs
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn

      - name: Install JS dependencies
        run: yarn install

      - name: Setup test database
        env:
          RAILS_ENV: test
        run: bundle exec rails db:schema:load

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: 325d29d9ac0a59974a66c6deb68b755a1466b8e00b2ac483ee992864513dfa36
        with:
          coverageCommand: bundle exec rails test:all
          debug: true
