name: CI

on: [push, pull_request]

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest   
    container: 
      image: ruby:2.6.5
      
    services:
      postgres:
        image: postgres:10.1
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: test
          POSTGRES_DB: wodtracker_test
          POSTGRES_PASSWORD: ""
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.13.0
    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install
        yarn install
    - name: Setup test databbase
      env:
        RAILS_ENV: test
      run: |
        bin/rails db:schema:load --trace

    - name: Run Tests
      run: |
        bundle exec rails test

