name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.6
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: runner
          POSTGRES_DB: wodtracker_test
          POSTGRES_PASSWORD: ""
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Install PostgreSQL client
        run: sudo apt-get -yqq install libpq-dev

      # https://github.com/guard/listen/blob/master/README.md#the-technical-details
      - name: Adjust inotify listeners for Listen
        run: |
          sudo sysctl fs.inotify.max_user_watches=524288
          sudo sysctl -p

      # Install Ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6
          bundler-cache: true

      # Install NodeJs
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install JS dependencies
        run: yarn install

      - name: Setup test database
        env:
          RAILS_ENV: test
        run: bundle exec rails db:schema:load
          
      - name: Test
        run: bundle exec rails test:all

      - uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{secrets.QLTY_COVERAGE_TOKEN}}
          files: coverage/.resultset.json

      # - name: Run RuboCop
      #   run: bundle exec rubocop --parallel
      - uses: reviewdog/action-rubocop@v2
        with:
          reporter: github-pr-check 
          skip_install: true
          use_bundler: true
