name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  verify:
    name: Build
    runs-on: ubuntu-latest
    env:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

    services:
      postgres:
        image: postgres:11.6
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: runner
          POSTGRES_DB: wodtracker_test
          POSTGRES_PASSWORD: ""
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Install PostgreSQL client
        run: sudo apt-get -yqq install libpq-dev

      # https://github.com/guard/listen/blob/master/README.md#the-technical-details
      - name: Adjust inotify listeners for Listen
        run: |
          sudo sysctl fs.inotify.max_user_watches=524288
          sudo sysctl -p

      # Install Ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      # Install NodeJs
      - uses: actions/setup-node@v1
        with:
          node-version: 12.13.1

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gem-

      - uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          yarn install --cache-folder ~/.cache/yarn

      - name: Setup test database
        env:
          RAILS_ENV: test
        run: bundle exec rails db:schema:load

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: 325d29d9ac0a59974a66c6deb68b755a1466b8e00b2ac483ee992864513dfa36
        with:
          coverageCommand: bundle exec rails test
          debug: true
